authors = ["Rafael Fourquet <fourquet.rafael@gmail.com>"]
name = "Bits"
uuid = "1654ce90-6ed3-553a-957f-9452c3a40996"
version = "0.2.0"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
